AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'Gemfile'
    - 'Rakefile'
  SuggestExtensions: false

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/MethodLength:
  Max: 35


Metrics/AbcSize:
  Max: 35

Metrics/ClassLength:
  Max: 300

Metrics/PerceivedComplexity:
  Max: 15

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: nested
